n_runs: 1
seed: 42
to_be_seeded:
  - basic
  - numpy
  - torch

default_grid:
  mutual_information: range(0.0, 11.0)
  nonzero_mutual_information: range(1.0, 11.0)
  dimensionality: range(1, 4)

hydra:
  mode: MULTIRUN
  sweep:
    dir: /home/foresti/infosedd/outputs/${now:%Y-%m-%d}
    subdir: ${estimator._target_}/${estimator.args.variant}/${estimator.args.loss_fn}/${distribution._target_}/${distribution_key}/N=${n_samples}/n_runs=${n_runs}/target_mutinfo=${distribution.mutual_information}/${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}
  sweeper:
    max_batch_size: 100 # Makes startup faster, see https://github.com/facebookresearch/hydra/issues/1324.
    params:
      ++n_samples: 1000000